AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Serverless v2 (Aurora3) 
Parameters:
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-0f4a6f26703335b0f
  DatabaseName:
    Description: DatabaseName
    Type: String
    Default: testdb

Resources:
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSSecret
      Description: "This is automatic generated Secrets Manager secret for an RDS DB instance"
      GenerateSecretString:
        # ユーザー名 "developersio"がハードコードされている
        SecretStringTemplate: '{"username": "admin"}'
        # パスワード "キーが生成され、マージされます。
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\$`&:{}()[]+*=^-|'
  
  SecretManagerVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      SubnetIds:
        - subnet-06e33ef6ca880faaa
        - subnet-0dd6588efa94d2d2e
      PrivateDnsEnabled: true
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      SecurityGroupIds:
        - sg-0be055c73d376d845
        - sg-097fef894bf28f5b3
        - sg-0db8b85557f84461f
      VpcEndpointType: Interface
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Principal: "*"
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref RDSSecret

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AWS::StackName}-DBSubnetGroup'
      SubnetIds: 
        - subnet-06e33ef6ca880faaa
        - subnet-0dd6588efa94d2d2e

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub '${AWS::StackName}-DBClusterParameterGroup'
      Family: aurora-mysql8.0
      Parameters:
        character_set_server: utf8
        character_set_client: utf8
        character_set_connection: utf8
        character_set_results: utf8
        character_set_database: utf8
        performance_schema: 1

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub '${AWS::StackName}-DBParameterGroup'
      Family: aurora-mysql8.0
      Parameters:
        general_log: 0
        slow_query_log: 1
        long_query_time: 5000
        log_output: FILE

  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.02.0
      VpcSecurityGroupIds:
        - sg-0be055c73d376d845
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      # PreferredMaintenanceWindow: Thu:18:35-Thu:19:05
      # PreferredBackupWindow: 18:05-18:35
      BackupRetentionPeriod: 7
      DatabaseName: !Ref 'DatabaseName'
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:password}}' ]]
      ServerlessV2ScalingConfiguration: 
        MaxCapacity: 16
        MinCapacity: 0.5

  DBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: instance1
      DBInstanceClass: db.serverless
      DBParameterGroupName: !Ref DBParameterGroup
      Engine: aurora-mysql
      EnablePerformanceInsights: false
      # PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
      PromotionTier: 0
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RDSSecret
      TargetId: !Ref DBCluster
      TargetType: AWS::RDS::DBCluster

  # DBInstance2:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     DBClusterIdentifier: !Ref 'DBCluster'
  #     DBInstanceClass: db.serverless
  #     DBParameterGroupName: !Ref 'DBParameterGroup'
  #     Engine: aurora-mysql
  #     EnablePerformanceInsights: true
  #     PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
  #     PromotionTier: 1
  #     AvailabilityZone: !Select
  #       - 1
  #       - !GetAZs
  #         Ref: AWS::Region

  ProxyRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: Allow
            Principal:
              Service: [ rds.amazonaws.com ]
      Policies:
        - PolicyName: DBProxyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                  # - secretsmanager:DescribeSecret
                Effect: Allow
                Resource:
                  - !Ref RDSSecret

  RDSProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      Auth:
      # Secrets Managerを利用してユーザ名とパスワードで認証
      # 予めSecretsは作成しておく必要があり
        - AuthScheme: SECRETS
          IAMAuth: DISABLED
          SecretArn: !Ref RDSSecret
      # 作成するRDS Proxyの名前
      DBProxyName: !Sub '${AWS::StackName}-DBProxy'
      # 2020/08/17時点でMySQLとPostgreSQLがサポートされている
      EngineFamily: MYSQL
      # Proxyとクライアント間の接続がアイドル状態の時に接続切断するまでの秒数
      IdleClientTimeout: 900
      # TLSが必須かどうか
      # RequireTLS: false
      # RDS Proxyに設定するIAM Role
      # 今回はSecrets Managerから値を取得して復号可能なRoleをアタッチ
      RoleArn: !GetAtt ProxyRole.Arn
      # RDS Proxyにアタッチするセキュリティグループ
      VpcSecurityGroupIds: 
        - sg-0db8b85557f84461f
      # RDS Proxyを構築するVPC Subnet
      VpcSubnetIds: 
        - subnet-06e33ef6ca880faaa
        - subnet-0dd6588efa94d2d2e

  ProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      DBProxyName: !Ref RDSProxy
      # Proxyが接続するRDS Auroraクラスターの識別子
      DBClusterIdentifiers: 
        - !Ref DBCluster
      TargetGroupName: default
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 60
        MaxIdleConnectionsPercent: 50
        ConnectionBorrowTimeout: 120
